language: python

cache:
    directories:
        - $HOME/.cache/pip

os: linux

matrix:
    include:
        - python: 3.5
          dist: xenial
          env: TOXENV=py35
        - python: 3.6
          dist: bionic
          env: TOXENV=py36
        - python: 3.7
          dist: bionic
          env: TOXENV=py37
        - python: 3.8
          dist: focal
          env: TOXENV=py38
        - python: 3.9
          dist: focal
          env: TOXENV=py39
        - python: 3.8
          dist: focal
          env: TOXENV=flake8

install:
  - "pip install -r requirements.d/dev.txt"

script:
  - "tox"

after_success:
  - codecov -e TRAVIS_OS_NAME TOXENV
