language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 3.6
          os: linux
          dist: xenial
          env: TOXENV=flake8
        - python: 2.7
          os: linux
          dist: xenial
          env: TOXENV=py27
        - python: 3.4
          os: linux
          dist: xenial
          env: TOXENV=py34
        - python: 3.5
          os: linux
          dist: xenial
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: xenial
          env: TOXENV=py36

install:
  - "pip install -r requirements.d/dev.txt"

script:
  - "tox"

after_success:
  - codecov -e TRAVIS_OS_NAME TOXENV

env:
  - PYTHONPATH=$PYTHONPATH:bepasty/
  - CODECOV_TOKEN="c5c64733-05bb-47d1-a581-22842f60600a"