language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.d/dev.txt"
script:
  - "pytest bepasty/ --cov=bepasty --cov-report xml --pep8 -m 'not needs_server'"
after_success:
  - "coveralls"
env:
  - PYTHONPATH=$PYTHONPATH:bepasty/
